// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// ---------------------------------------------------------------------

#ifndef _BEHAVIAC_MEMBER_VISITOR_H_
#define _BEHAVIAC_MEMBER_VISITOR_H_

#include "behaviac_agent_headers.h"

// Agent property and method handlers


struct PROPERTY_TYPE_cpp_agent_int_val { };
template<> inline int& cpp_agent::_Get_Property_<PROPERTY_TYPE_cpp_agent_int_val>()
{
	return this->int_val;
}

struct METHOD_TYPE_cpp_agent_HelloCppAgent { };
template<> inline void cpp_agent::_Execute_Method_<METHOD_TYPE_cpp_agent_HelloCppAgent>()
{
	this->cpp_agent::HelloCppAgent();
}


#endif // _BEHAVIAC_MEMBER_VISITOR_H_
