// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// ---------------------------------------------------------------------

#ifndef _BEHAVIAC_AGENT_PROPERTIES_H_
#define _BEHAVIAC_AGENT_PROPERTIES_H_

#include "behaviac_agent_headers.h"
#include "behaviac_agent_member_visitor.h"

namespace behaviac
{
	// ---------------------------------------------------------------------
	// Delegate methods
	// ---------------------------------------------------------------------

	inline void FunctionPointer_behaviac_Agent_LogMessage(char* param0) { behaviac::Agent::LogMessage(param0); }

	inline void Set_cpp_agent_int_val(Agent* self, int value) { ((cpp_agent*)self)->_Get_Property_<PROPERTY_TYPE_cpp_agent_int_val, int >() = value; };
	inline const void* Get_cpp_agent_int_val(Agent* self) { return &((cpp_agent*)self)->_Get_Property_<PROPERTY_TYPE_cpp_agent_int_val, int >(); };

	inline void FunctionPointer_cpp_agent_HelloCppAgent(Agent* self) { ((cpp_agent*)self)->_Execute_Method_<METHOD_TYPE_cpp_agent_HelloCppAgent, void >(); }
	inline void FunctionPointer_cpp_agent_LogMessage(char* param0) { cpp_agent::LogMessage(param0); }
}
#endif // _BEHAVIAC_AGENT_PROPERTIES_H_
