// -------------------------------------------------------------------------------
// THIS FILE IS ORIGINALLY GENERATED BY THE DESIGNER.
// YOU ARE ONLY ALLOWED TO MODIFY CODE BETWEEN '///<<< BEGIN' AND '///<<< END'.
// PLEASE MODIFY AND REGENERETE IT IN THE DESIGNER FOR CLASS/MEMBERS/METHODS, ETC.
// -------------------------------------------------------------------------------

#ifndef _BEHAVIAC_CPP_AGENT_H_
#define _BEHAVIAC_CPP_AGENT_H_

#include "behaviac_headers.h"

///<<< BEGIN WRITING YOUR CODE FILE_INIT

///<<< END WRITING YOUR CODE

class cpp_agent : public behaviac::Agent
///<<< BEGIN WRITING YOUR CODE cpp_agent
///<<< END WRITING YOUR CODE
{
public:
	cpp_agent();
	virtual ~cpp_agent();

	BEHAVIAC_DECLARE_AGENTTYPE(cpp_agent, behaviac::Agent)

	private: int int_val;

	private: void HelloCppAgent();

///<<< BEGIN WRITING YOUR CODE CLASS_PART

///<<< END WRITING YOUR CODE
};

///<<< BEGIN WRITING YOUR CODE FILE_UNINIT

///<<< END WRITING YOUR CODE

#endif
