// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// ---------------------------------------------------------------------

#ifndef _BEHAVIAC_MEMBER_VISITOR_H_
#define _BEHAVIAC_MEMBER_VISITOR_H_

#include "behaviac_agent_headers.h"

// Agent property and method handlers


struct METHOD_TYPE_PlayerAgent_autoFight { };
template<> inline void PlayerAgent::_Execute_Method_<METHOD_TYPE_PlayerAgent_autoFight>()
{
	this->PlayerAgent::autoFight();
}

struct METHOD_TYPE_PlayerAgent_autoMove { };
template<> inline void PlayerAgent::_Execute_Method_<METHOD_TYPE_PlayerAgent_autoMove>()
{
	this->PlayerAgent::autoMove();
}

struct METHOD_TYPE_PlayerAgent_canFight { };
template<> inline bool PlayerAgent::_Execute_Method_<METHOD_TYPE_PlayerAgent_canFight>()
{
	return this->PlayerAgent::canFight();
}

struct METHOD_TYPE_PlayerAgent_canMove { };
template<> inline bool PlayerAgent::_Execute_Method_<METHOD_TYPE_PlayerAgent_canMove>()
{
	return this->PlayerAgent::canMove();
}


#endif // _BEHAVIAC_MEMBER_VISITOR_H_
