// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// ---------------------------------------------------------------------

#ifndef _BEHAVIAC_AGENT_PROPERTIES_H_
#define _BEHAVIAC_AGENT_PROPERTIES_H_

#include "behaviac_agent_headers.h"
#include "behaviac_agent_member_visitor.h"

namespace behaviac
{
	// ---------------------------------------------------------------------
	// Delegate methods
	// ---------------------------------------------------------------------

	inline void FunctionPointer_behaviac_Agent_LogMessage(char* param0) { behaviac::Agent::LogMessage(param0); }
	inline void FunctionPointer_PlayerAgent_autoFight(Agent* self) { ((PlayerAgent*)self)->_Execute_Method_<METHOD_TYPE_PlayerAgent_autoFight, void >(); }
	inline void FunctionPointer_PlayerAgent_autoMove(Agent* self) { ((PlayerAgent*)self)->_Execute_Method_<METHOD_TYPE_PlayerAgent_autoMove, void >(); }
	inline bool FunctionPointer_PlayerAgent_canFight(Agent* self) { return (bool)((PlayerAgent*)self)->_Execute_Method_<METHOD_TYPE_PlayerAgent_canFight, bool >(); }
	inline bool FunctionPointer_PlayerAgent_canMove(Agent* self) { return (bool)((PlayerAgent*)self)->_Execute_Method_<METHOD_TYPE_PlayerAgent_canMove, bool >(); }
	inline void FunctionPointer_PlayerAgent_LogMessage(char* param0) { PlayerAgent::LogMessage(param0); }
}
#endif // _BEHAVIAC_AGENT_PROPERTIES_H_
