// -------------------------------------------------------------------------------
// THIS FILE IS ORIGINALLY GENERATED BY THE DESIGNER.
// YOU ARE ONLY ALLOWED TO MODIFY CODE BETWEEN '///<<< BEGIN' AND '///<<< END'.
// PLEASE MODIFY AND REGENERETE IT IN THE DESIGNER FOR CLASS/MEMBERS/METHODS, ETC.
// -------------------------------------------------------------------------------

#ifndef _BEHAVIAC_PLAYERAGENT_H_
#define _BEHAVIAC_PLAYERAGENT_H_

#include "behaviac_headers.h"

///<<< BEGIN WRITING YOUR CODE FILE_INIT

///<<< END WRITING YOUR CODE

class PlayerAgent : public behaviac::Agent
///<<< BEGIN WRITING YOUR CODE PlayerAgent
///<<< END WRITING YOUR CODE
{
public:
	PlayerAgent();
	virtual ~PlayerAgent();

	BEHAVIAC_DECLARE_AGENTTYPE(PlayerAgent, behaviac::Agent)

	private: void autoFight();

	private: void autoMove();

	private: bool canFight();

	private: bool canMove();

///<<< BEGIN WRITING YOUR CODE CLASS_PART
public:
	void 	setOwner(Player* p);
private:
	Player* owner_;
///<<< END WRITING YOUR CODE
};

///<<< BEGIN WRITING YOUR CODE FILE_UNINIT

///<<< END WRITING YOUR CODE

#endif
