// -------------------------------------------------------------------------------
// THIS FILE IS ORIGINALLY GENERATED BY THE DESIGNER.
// YOU ARE ONLY ALLOWED TO MODIFY CODE BETWEEN '///<<< BEGIN' AND '///<<< END'.
// PLEASE MODIFY AND REGENERETE IT IN THE DESIGNER FOR CLASS/MEMBERS/METHODS, ETC.
// -------------------------------------------------------------------------------

#include "PlayerAgent.h"

///<<< BEGIN WRITING YOUR CODE FILE_INIT

///<<< END WRITING YOUR CODE

PlayerAgent::PlayerAgent()
{
///<<< BEGIN WRITING YOUR CODE CONSTRUCTOR
    owner_ = NULL;
///<<< END WRITING YOUR CODE
}

PlayerAgent::~PlayerAgent()
{
///<<< BEGIN WRITING YOUR CODE DESTRUCTOR

///<<< END WRITING YOUR CODE
}

void PlayerAgent::autoFight()
{
///<<< BEGIN WRITING YOUR CODE autoFight
    owner_->autoFight();
///<<< END WRITING YOUR CODE
}

void PlayerAgent::autoMove()
{
///<<< BEGIN WRITING YOUR CODE autoMove
    owner_->autoMove();
///<<< END WRITING YOUR CODE
}

bool PlayerAgent::canFight()
{
///<<< BEGIN WRITING YOUR CODE canFight
	return true;
///<<< END WRITING YOUR CODE
}

bool PlayerAgent::canMove()
{
///<<< BEGIN WRITING YOUR CODE canMove
	return true;
///<<< END WRITING YOUR CODE
}


///<<< BEGIN WRITING YOUR CODE FILE_UNINIT
void PlayerAgent::setOwner(Player* p)
{
    owner_ = p;
}

///<<< END WRITING YOUR CODE
